<?php
/*
    FantasyFootball Symfony2 bundles - Symfony2 bundles collection to handle fantasy football tournament 
    Copyright (C) 2017  Bertrand Madet

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
namespace FantasyFootball\TournamentCoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceRepository extends EntityRepository
{
    public function getQueryBuilderForRaceByEditionOrLesser($editionId)
    {
        $qb = $this->createQueryBuilder('r');
        $qb->where($qb->expr()->lte('r.edition', $editionId));
        $qb->orderBy('r.frenchName');
        return $qb;
    }
    
    public function getRaceByName($name)
    {
      $qb = $this->createQueryBuilder('r');
      return $qb->where('r.frenchName = :name')
        ->orWhere('r.englishName = :name')
	->orWhere('r.englishName2 = :name')
	->setParameter('name',$name)
        ->getQuery()->getOneOrNullResult();
    }
}
