_ws_get_coach_list:
  path:     /CoachList/{edition}
  defaults: { _controller: FantasyFootballTournamentCoreBundle:Coach:getCoachList }
  requirements:
    edition:  \d+
_ws_get_coaches:
  path:     /Coachs/{edition}
  defaults: { _controller: FantasyFootballTournamentCoreBundle:Coach:getCoachList }
  requirements:
    edition:  \d+
_ws_get_coach:
  path:     /Coach/{coachId}
  defaults: { _controller: FantasyFootballTournamentCoreBundle:Coach:getCoach }
  requirements:
    coachId:  \d+
