_add_game:
   path:    /schedule/{edition}/{round}
   defaults: { _controller: FantasyFootballTournamentAdminBundle:Game:Schedule,round: -1 }
   requirements:
      edition:  \d+
      round:  \d+

_modify_game:
   path:    /modify/{gameId}
   defaults: { _controller: FantasyFootballTournamentAdminBundle:Game:Modify }
   requirements:
      gameId:  \d+

_resume_game:
   path:    /resume/{gameId}
   defaults: { _controller: FantasyFootballTournamentAdminBundle:Game:Resume }
   requirements:
      gameId:  \d+

_delete_game:
   path:    /delete/{gameId}
   defaults: { _controller: FantasyFootballTournamentAdminBundle:Game:Delete }
   requirements:
      gameId:  \d+

_summarize:
   path:    /summarize/{edition}/{round}
   defaults: { _controller: FantasyFootballTournamentAdminBundle:Game:Summarize }
   requirements:
      edition:  \d+
      round:  \d+
